export const TYPES = {
    IHttpServerService: Symbol.for('IHttpServerService'),
    IWsServerService: Symbol.for('IWsServerService'),
    IApolloServerService: Symbol.for('IApolloServerService'),
    IGraphQLSchemaService: Symbol.for('IGraphQLSchemaService'),
    IDatabaseService: Symbol.for('IDatabaseService'),
    ICloudinaryService: Symbol.for('ICloudinaryService'),
    IFileRepository: Symbol.for('IFileRepository'),
    IChatRepository: Symbol.for('IChatRepository'),
    IChatService: Symbol.for('IChatService'),
    ChatResolver: Symbol.for('ChatResolver'),
    IUserRepository: Symbol.for('IUserRepository'),
    IUserService: Symbol.for('IUserService'),
    UserResolver: Symbol.for('UserResolver'),
    INotificationRepository: Symbol.for('INotificationRepository'),
    INotificationService: Symbol.for('INotificationService'),
}