export const TYPES = {
    IHttpServerService: Symbol.for('IHttpServerService'),
    IWsServerService: Symbol.for('IWsServerService'),
    IApolloServerService: Symbol.for('IApolloServerService'),
    IGraphQLSchemaService: Symbol.for('IGraphQLSchemaService'),
    IDatabaseService: Symbol.for('IDatabaseService'),
    ICloudinaryService: Symbol.for('ICloudinaryService'),
    IFileRepository: Symbol.for('IFileRepository'),
    IChatRepository: Symbol.for('IChatRepository'),
    IChatService: Symbol.for('IChatService'),
    IUserRepository: Symbol.for('IUserRepository'),
    IUserService: Symbol.for('IUserService'),
    INotificationRepository: Symbol.for('INotificationRepository'),
    INotificationService: Symbol.for('INotificationService'),
    IPostRepository: Symbol.for('IPostRepository'),
    IPostService: Symbol.for('IPostService'),
    IPostLoader: Symbol.for('IPostLoader'),
    ISearchHistoryRepository: Symbol.for('ISearchHistoryRepository'),
    ISearchHistoryService: Symbol.for('ISearchHistoryService'),
}