services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8001:${PORT}"
      - "9229:9229" # for debugging
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PORT: "${PORT}"
      MONGO_URI: "${MONGO_URI}"
      NODE_ENV: "${NODE_ENV}"
      SECRET_KEY: "${SECRET_KEY}"
    command: npm run build:dev